name: "build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sphinx build
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache miniconda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os}}-miniconda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os}}-miniconda
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os}}-pip-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os}}-pip
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        auto-activate-base: false
        channels: conda-forge
        channel-priority: strict
        show-channel-urls: true
        environment-file: environment.yml
        activate-environment: doc
        use-only-tar-bz2: true
    - name: Collect info
      shell: pwsh
      run: |
        conda info
        conda list
        python -m pip cache dir
    - name: Sphinx build
      shell: pwsh
      run: |
        sphinx-build -M html doc publish -j auto
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: publish/html

